### ISSUE TITLE
Does it support automatically delete old log files?

### ISSUE THREAD

**Issue by bigbang489** [zubairehman/Flogs#31]
I just want to keep log files for the latest 7 days, all the log beyond that time will be automatically deleted
Has it been supported, and how to config it?

**Comment by slc1973** [comment]
You can use deleteAllLogsByFilter() for this, see end of README.md please

**Comment by slc1973** [comment]
Hello @EinatK!

I was successful with upgrade of my development environment, see below:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.6.0-12.0.pre.390, on Ubuntu 18.04.6 LTS 5.4.0-87-generic, locale de_DE.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
[✓] VS Code (version 1.61.1)
[✓] Connected device (2 available)

• No issues found!
```
Upgraded Flogs to version 2.0.0-alpha-01
Started main.dart from /Flogs/example/lib folder and created some log messages with "Log Event"-button.
After some time i pushed "Delete Logs by Filter (older then 10 seconds)"-button and logs older then 10 seconds are deleted.
I can still confirm that deleteAllLogsByFilter() is running fine, see log below.
```
I/flutter (23896): {2021-10-19 21:07:05} {LogLevel.WARNING} {HomePage} {_buildRow1} {Log text/descritption goes here} {Warning (the type could be anything)} {1634670425091}
I/flutter (23896): Deleted 16 logs
```

How deleteAllLogsByFilter() is exactly called in example code?
```
          FLog.deleteAllLogsByFilter(filters: [
            Filter.lessThan(DBConstants.FIELD_TIME_IN_MILLIS,
                DateTime.now().millisecondsSinceEpoch - 1000 * 10)
          ]);
```
Filter.lessThan() is part from package sembast and still in version "^3.0.2" defined in pubspec.yaml...

**Comment by slc1973** [comment]
@zubairehman issue can be closed

**Comment by EinatK** [comment]
@slc1973  Thanks so much ! 
I still don't see the filter class but i added the sembast package on my own and now it works.
